### ISSUE TITLE
Automatically place cursor in password field in unlock dialog when dataset is encrypted with password

### ISSUE THREAD

**Issue by CodingSpiderFox** [truenas/linux#165]
![image](https://github.com/truenas/linux/assets/25173078/40665790-33bd-44c7-846c-2f88704b9432)

This speeds up the unlocking process and helps those people primarily using the keyboard very much

**Comment by william-gr** [comment]
Please file suggestions in our Jira tracker: https://ixsystems.atlassian.net/
